-- Base class: Mage
return {
    ArcaneBolt = {
        Name        = 'ArcaneBolt',
        Cooldown    = 0.5,
        ManaCost    = 0,
        Range       = 40,
        Damage      = 9,
        Type        = 'Magic',
        AnimationId = 0,
        Visual      = 'BlueProjectile',
    },
    ArcanePulse = {
        Name        = 'ArcanePulse',
        Cooldown    = 15,
        ManaCost    = 25,
        Radius      = 8,
        Damage      = 16,
        Knockback   = 4,
        AnimationId = 0,
        Visual      = 'Shockwave',
    },
    ManaWellspring = {
        Name    = 'ManaWellspring',
        Type    = 'Passive',
        Effects = {
            {Stat='ManaRegenPercent', Value=0.02},
        },
    },
    HexOfWithering = {
        Name            = 'HexOfWithering',
        Cooldown        = 20,
        ManaCost        = 40,
        Duration        = 9,
        DamageReductionPct = 0.05,
        DamageTakenPct  = 0.05,
        BackHealPct     = 0.004,
        AnimationId     = 0,
        Visual          = 'DarkSigil',
    },
    DeathsShroud = {
        Name         = 'DeathsShroud',
        Cooldown     = 8,
        ManaCost     = 30,
        DashRange    = 8,
        TrailDuration= 3,
        TrailDamage  = 20,
        TrailSlowPct = 0.30,
        AnimationId  = 0,
        Visual       = 'PoisonTrail',
    },
    ArcaneOverload = {
        Name         = 'ArcaneOverload',
        Cooldown     = 6,
        ManaCost     = 15,
        Duration     = 4,
        DamageBuffPct= 0.20,
        BacklashHPpct= 0.02,
        AnimationId  = 0,
        Visual       = 'OverloadGlow',
    },
}
