-- Base class: Striker
return {
    BrutalUppercut = {
        Name        = 'BrutalUppercut',
        Cooldown    = 0.7692,
        Damage      = 10,
        AnimationId = 0,
        Visual      = 'UppercutShock',
    },
    LungingStrike = {
        Name        = 'LungingStrike',
        Cooldown    = 8,
        ManaCost    = 25,
        Range       = 6,
        Damage      = 15,
        SlowPct     = 0.10,
        AnimationId = 0,
        Visual      = 'DashSlash',
    },
    GlacialClaw = {
        Name        = 'GlacialClaw',
        Cooldown    = 6,
        Damage      = 12,
        Projectiles = 3,
        ConeAngle   = 60,
        AppliesChillPct = 0.15,
        ChillDuration= 2,
        Type        = 'Magic',
        AnimationId = 0,
        Visual      = 'IceClaw',
    },
    VoidAbsorption = {
        Name            = 'VoidAbsorption',
        Cooldown        = 18,
        DamageReductionPct = 0.30,
        Duration        = 2,
        AnimationId     = 0,
        Visual          = 'VoidStance',
    },
    CrimsonDomain = {
        Name            = 'CrimsonDomain',
        Cooldown        = 20,
        Duration        = 4,
        DamageBuffPct   = 0.10,
        AoERadius       = 5,
        AnimationId     = 0,
        Visual          = 'RedZone',
    },
}
