-- Base class: Warrior
return {
    Slash = {
        Name        = 'Slash',
        Cooldown    = 0.8333,
        Range       = 5,
        Damage      = 9,
        AnimationId = 0,
        Visual      = 'SwordArcFlash',
    },
    UnbreakableCharge = {
        Name          = 'UnbreakableCharge',
        Cooldown      = 10,
        Range         = 5,
        Damage        = 35,
        Knockdown     = true,
        KnockdownTime = 0.75,
        DamageReduction         = 0.20,
        DamageReductionDuration = 2,
        AnimationId   = 0,
        Visual        = 'Shockwave',
    },
    BattleHardened = {
        Name    = 'BattleHardened',
        Type    = 'Passive',
        Effects = {
            {Stat='PhysicalResistance', Value=0.02},
            {Stat='MaxHPPercent',         Value=0.02},
        },
        Trigger = {Type='HealthBelowPercent', Value=0.20},
    },
    LaceratingStrike = {
        Name                   = 'LaceratingStrike',
        Cooldown               = 8,
        Damage                 = 25,
        BleedStacks            = 2,
        BleedStackDamagePct    = 0.10,
        MaxBleedStacks         = 5,
        AnimationId            = 0,
        Visual                 = 'BleedTrail',
    },
    VoidInfusion = {
        Name          = 'VoidInfusion',
        Cooldown      = 18,
        Damage        = 40,
        ShieldPerEnemyHit = true,
        AnimationId   = 0,
        Visual        = 'VoidVortex',
    },
    UnyieldingGuard = {
        Name             = 'UnyieldingGuard',
        Cooldown         = 25,
        Range            = 8,
        Taunt            = true,
        TauntDuration    = 3,
        EnemyDRReduction = 0.05,
        ShieldPercentMaxHP = 0.15,
        AnimationId      = 0,
        Visual           = 'GoldenShield',
    },
}
